/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bun_client.view;

import bun_client.controler.CallCenterControler;
import bun_client.controler.ItemControler;
import bun_client.observerImpl.CustomerObserverImpl;
import bun_common.dto.ItemDto;
import bun_common.dto.OrdersDto;
import bun_common.observer.CustomerObserver;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kavindu
 */
public class Report extends javax.swing.JDialog {
    private String date;
    private String oid = "";
    private int count=0;
    private CustomerObserver customerObserver;
    /**
     * Creates new form Report
     */
    public Report(java.awt.Frame parent, boolean modal , String date) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null); 
        this.date=date;
        load();
        
         try {
            customerObserver=new CustomerObserverImpl(this);
            CallCenterControler.customerObs(customerObserver);
        } catch (RemoteException ex) {
            Logger.getLogger(ChefForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException | MalformedURLException ex) {
            Logger.getLogger(ChefForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
        Logger.getLogger(ChefForm.class.getName()).log(Level.SEVERE, null, ex);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        custNameTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        custAddressTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        custTelTxt = new javax.swing.JTextField();
        itemNameTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dateTxt = new javax.swing.JTextField();
        typeLbl = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        qtyTxt = new javax.swing.JTextField();
        chef = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 51));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("   Today Report");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTable1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Customer", "Qty", "Item", "Type", "Count"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Customer Name");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 22, -1, -1));

        custNameTxt.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPanel3.add(custNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 16, 149, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Customer Address");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 54, -1, -1));

        custAddressTxt.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPanel3.add(custAddressTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 48, 149, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Customer Tel");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 92, -1, -1));

        custTelTxt.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPanel3.add(custTelTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 86, 149, -1));

        itemNameTxt.setEditable(false);
        itemNameTxt.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPanel3.add(itemNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 118, 149, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Item Name");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 124, -1, -1));

        dateTxt.setEditable(false);
        dateTxt.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPanel3.add(dateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 7, 147, -1));

        typeLbl.setBackground(new java.awt.Color(255, 81, 117));
        typeLbl.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        typeLbl.setOpaque(true);
        jPanel3.add(typeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 39, 91, 75));

        jButton1.setBackground(new java.awt.Color(153, 0, 153));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("Update");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 141, 147, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Item Qty");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 156, -1, -1));

        qtyTxt.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPanel3.add(qtyTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 149, -1));
        jPanel3.add(chef, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 7, 70, 26));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText(" Today finished Orders :");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText(" ");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 24, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bun_client/assest/Food___Cakes_and_Sweet_Fruits_and_berries_on_a_chocolate_biscuit_097359_.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -2, 590, 190));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       
        
        int x=jTable1.getSelectedRow();
        String oid=""+jTable1.getValueAt(x,0);
        try {
            OrdersDto ordersDto=CallCenterControler.searchOrder(oid);
            
            if(!this.oid.equalsIgnoreCase(oid)){
                CallCenterControler.release(this.oid);
                this.oid=oid;
            }
            if (ordersDto != null) {
                boolean isReserved = CallCenterControler.reserve(oid);
                if (isReserved) {
                   ItemDto itemDto=ItemControler.serarchItm(ordersDto.getItemCode());
                custNameTxt.setText(ordersDto.getName());
                custAddressTxt.setText(ordersDto.getAddress());
                custTelTxt.setText(ordersDto.getTel());
                qtyTxt.setText(""+ordersDto.getQty()); 
                itemNameTxt.setText(itemDto.getItemName());
                dateTxt.setText(ordersDto.getDate());
                typeLbl.setText("          "+ordersDto.getType());
                chef.setText(ordersDto.getChefName());
            
                } else {
                    JOptionPane.showMessageDialog(null,"Reseved");
                custNameTxt.setText("");
                custAddressTxt.setText("");
                custTelTxt.setText("");
                qtyTxt.setText(""); 
                itemNameTxt.setText("");
                dateTxt.setText("");
                typeLbl.setText("");
                chef.setText("");
                }
            } else {
                JOptionPane.showMessageDialog(this, "No Customer found");
            }
            
        } catch (Exception ex) {
            Logger.getLogger(Report.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
     int x=jTable1.getSelectedRow();
        String oid=""+jTable1.getValueAt(x,0);
        int qty=Integer.parseInt(qtyTxt.getText());
        String item=""+jTable1.getValueAt(x,3);
        
        String cust=""+jTable1.getValueAt(x,1);
        OrdersDto dto=null;
        ItemDto itemDto=null;
        try {
           itemDto=ItemControler.serarchItm(item);
           dto =CallCenterControler.searchOrder(oid);
        } catch (Exception ex) {
            Logger.getLogger(Report.class.getName()).log(Level.SEVERE, null, ex);
        }
        OrdersDto ordersDto=new OrdersDto(dto.getOid(),dateTxt.getText(),qty,itemDto.getItemCode(),cust,custNameTxt.getText(),custAddressTxt.getText(),custTelTxt.getText(),dto.getType(),dto.getStartTime(),dto.getEndTime(),dto.getChefName(),dto.getCount());
        try {
            boolean b= CallCenterControler.updateOrder(ordersDto);
            if (b) {
                JOptionPane.showMessageDialog(null,"The order is updated");
            }else{
                JOptionPane.showMessageDialog(null,"Sorry ! Order Update Is Failed !","",JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception ex) {
            Logger.getLogger(Report.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Report dialog = new Report(new javax.swing.JFrame(), true,"");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chef;
    private javax.swing.JTextField custAddressTxt;
    private javax.swing.JTextField custNameTxt;
    private javax.swing.JTextField custTelTxt;
    private javax.swing.JTextField dateTxt;
    private javax.swing.JTextField itemNameTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField qtyTxt;
    private javax.swing.JLabel typeLbl;
    // End of variables declaration//GEN-END:variables

    private void load() {
              DefaultTableModel dtm=(DefaultTableModel)jTable1.getModel();
                 dtm.setRowCount(0);
      
        try {
            List<OrdersDto>list=CallCenterControler.searchDate(date); 
            
            if(list==null){
                JOptionPane.showMessageDialog(null,"Empty Orders at Today !");
            }else{
                      
            for (OrdersDto ordersDto : list) {
                count++;
                Object []row={ordersDto.getOid(),ordersDto.getCid(),ordersDto.getQty(),ordersDto.getItemCode(),ordersDto.getType(),ordersDto.getCount()};
                dtm.addRow(row);
            }
            jLabel8.setText(""+count);
          }
        } catch (Exception ex) {
            Logger.getLogger(Report.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }
    public void setMessage(String message){
        JOptionPane.showMessageDialog(this, message);
    }
}
